#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

pattern = r'\.|/|;|\'|`|\[|\]|<|>|\?|:|"|\{|\}|\~|!|@|#|\$|\^|&|=|\+|，|。|、|；|‘|’|【|】|·|！|…|（|）'




test_str = "I AM INTERESTED IN INFORMATION ON THE PROVISION OF CURRENT AWARENESS BULLETINS, ESPECIALLY SDI SERVICES IN ANY INSTITUTION, E.G. ACADEMIC LIBRARIES, INDUSTRY, AND IN ANY SUBJECT FIELD.  SDI, SELECTIVE DISSEMINATION OF INFORMATION, CURRENT AWARENESS BULLETINS, INFORMATION BULLETINS."
test_str = test_str.lower()
print(test_str)
print(re.split(pattern,test_str))




test_str = "SOME CHARACTERISTICS OF SDI SYSTEMS (EXPERIENCE OF THE CENTRAL SCIENTIFIC RESEARCH INSTITUTE FOR INFORMATION AND ECONOMIC RESEARCH FOR THE OIL INDUSTRY). DISCUSSES THE SDI SYSTEM DEVELOPED BY THE CENTRAL SCIENTIFIC RESEARCH INSTITUTE FOR INFORMATION AND ECONOMIC RESEARCH FOR THE OIL INDUSTRY. THE SYSTEM IS USED TO PROVIDE SDI TO 2 MAIN GROUPS OF USERS' SCIENTISTS AND MANAGEMENT OFFICERS. AS FAR AS THE 1ST USER GROUP IS CONCERNED THE OPERATION OF THE SDI SERVICE IS SUCCESSFUL. IN 1978, OUT OF THE 150,000 SDI ITEMS SENT OUT, ONLY 15% WERE RETURNED BY THE USERS AS IRRELEVANT. AS FAR AS THE LATTER USER GROUP IS CONCERNED, THE CONTACT BETWEEN THE INFORMATION CENTRE AND THE MEMBERS OF THE GROUP IS NOT SATISFACTORY. A SURVEY OF THE SDI REQUIREMENTS WAS THEREFORE CARRIED OUT. RESULTS ARE PRESENTED."
test_str = test_str.lower()
print(test_str)
print(re.split(pattern,test_str))